24/Dec/2024 19:52:09    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
24/Dec/2024 19:52:09    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 18492   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
24/Dec/2024 20:02:42    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
24/Dec/2024 20:02:42    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 18492   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
24/Dec/2024 20:03:32    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
24/Dec/2024 20:03:32    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 18492   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
24/Dec/2024 20:03:32    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
24/Dec/2024 20:03:32    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 18492   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
